---
title: "CS Q4.Rmd"
author: "Daniel Byrne"
date: "October 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=FALSE, message=FALSE}

library(data.table)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(knitr)
library(pander)
library(reshape2)
library(usmap)
library(tidyr)
library(mosaic)
library(ggformula)

beers = read.csv("beers.csv", header = TRUE,strip.white = TRUE)
colnames(beers) <- c("Beer_Name","Beer_ID","ABV","IBU","Brewery_ID","Style","Ounces")
beers$Brewery_ID <-as.character(beers$Brewery_ID)
beers$Beer_ID <-as.character(beers$Beer_ID)

breweries = read.csv("breweries.csv", header = TRUE,strip.white = TRUE)
colnames(breweries) <- c("Brewery_ID","Brewery_Name","City","State")
breweries$Brewery_ID <-as.character(breweries$Brewery_ID)

brewery_beer <- merge(breweries, beers, by=c("Brewery_ID"))
```

### Statistical Analysis of Beer Variables by State
```{r, warning=FALSE}
ibuByState <- favstats(IBU~State,data=brewery_beer)
abvByState <- favstats(ABV~State,data=brewery_beer)

#order by median
ibuByState <- ibuByState[order(ibuByState$median,decreasing = TRUE),]
abvByState <- abvByState[order(abvByState$median,decreasing = TRUE),]

# chart and plot top 10 median IBU by State
gf_col(median~State,data=head(ibuByState,10), title="Top 10 Median IBU by State")
kable(head(ibuByState,10), align = "l", row.names = FALSE, caption="Top 10 Median IBU by State") %>%
  kable_styling(c("striped","condensed"), full_width = F, position = "left", font_size = 10)

# chart and plot top 10 median ABV by State
gf_col(median~State,data=head(abvByState,10), title="Top 10 Median ABV by State")
kable(head(abvByState,10), align = "l", row.names = FALSE, caption="Top 10 Median ABV by State") %>%
  kable_styling(c("striped","condensed"), full_width = F, position = "left", font_size = 10)

```